import { pool } from './connection';
const dishes: any[] = [
  { name_en:'Stir-fried Bok Choy', name_zh:'清炒小白菜', category:'vegetable', calories:80, protein_g:3.2, carbs_g:7.1, fat_g:4.5, description:'A quick, light stir-fry that lets the natural sweetness of bok choy shine.', ingredients:[{name_en:'Bok choy',name_zh:'小白菜',amount_g:300,note:'halved lengthwise'},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15},{name_en:'Salt',name_zh:'盐',amount_g:3},{name_en:'Oyster sauce',name_zh:'蚝油',amount_g:10}], steps:['Heat oil in wok over high heat until shimmering.','Add garlic and stir-fry for 20 seconds until fragrant.','Add bok choy and toss constantly for 2 minutes.','Season with salt and oyster sauce, toss once more and serve.']},
  { name_en:'Mapo Tofu', name_zh:'麻婆豆腐', category:'vegetable', calories:180, protein_g:10.5, carbs_g:8.2, fat_g:11.0, description:'Silky tofu in a bold, numbing chilli-bean sauce — a Sichuan classic.', ingredients:[{name_en:'Silken tofu',name_zh:'嫩豆腐',amount_g:400,note:'cubed 2cm'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:20},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Ginger',name_zh:'姜',amount_g:8,note:'minced'},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:3},{name_en:'Spring onion',name_zh:'葱',amount_g:20,note:'sliced'},{name_en:'Light soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:8,note:'mixed with 2 tbsp water'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Boil tofu cubes in salted water 1 min, drain.','Heat oil, fry doubanjiang and peppercorn 1 min.','Add garlic and ginger, stir-fry 30 seconds.','Add 200ml water, bring to simmer, slide in tofu.','Add soy sauce, thicken with cornstarch slurry.','Top with spring onion and serve.']},
  { name_en:'Tomato and Egg Stir-fry', name_zh:'番茄炒蛋', category:'vegetable', calories:145, protein_g:8.0, carbs_g:10.5, fat_g:7.5, description:'The most beloved weeknight dish in China.', ingredients:[{name_en:'Tomatoes',name_zh:'番茄',amount_g:300,note:'cut into wedges'},{name_en:'Eggs',name_zh:'鸡蛋',amount_g:150,note:'3 eggs, beaten'},{name_en:'Sugar',name_zh:'糖',amount_g:5},{name_en:'Salt',name_zh:'盐',amount_g:3},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20},{name_en:'Spring onion',name_zh:'葱',amount_g:10,note:'sliced'}], steps:['Heat oil, pour in eggs, scramble until just set, set aside.','In same wok, add tomato wedges, stir-fry 2 min.','Return eggs, add salt and sugar, toss 30 seconds.','Garnish with spring onion and serve.']},
  { name_en:'Garlic Spinach', name_zh:'蒜蓉菠菜', category:'vegetable', calories:70, protein_g:4.1, carbs_g:5.5, fat_g:3.8, description:'Blanched spinach tossed with fragrant garlic oil and sesame.', ingredients:[{name_en:'Spinach',name_zh:'菠菜',amount_g:300,note:'trimmed'},{name_en:'Garlic',name_zh:'大蒜',amount_g:15,note:'finely minced'},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:8},{name_en:'Salt',name_zh:'盐',amount_g:3},{name_en:'Cooking oil',name_zh:'食用油',amount_g:10}], steps:['Blanch spinach 30 seconds in boiling salted water, drain and squeeze dry.','Heat oil, fry garlic 30 seconds until golden.','Toss spinach with garlic oil, sesame oil and salt.']},
  { name_en:'Di San Xian', name_zh:'地三鲜', category:'vegetable', calories:210, protein_g:4.0, carbs_g:22.0, fat_g:11.0, description:'Aubergine, potato and green pepper braised in a savoury soy glaze.', ingredients:[{name_en:'Aubergine',name_zh:'茄子',amount_g:200,note:'chunks'},{name_en:'Potato',name_zh:'土豆',amount_g:150,note:'chunks'},{name_en:'Green pepper',name_zh:'青椒',amount_g:80,note:'sliced'},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Oyster sauce',name_zh:'蚝油',amount_g:10},{name_en:'Sugar',name_zh:'糖',amount_g:5},{name_en:'Cooking oil',name_zh:'食用油',amount_g:30}], steps:['Deep-fry potato chunks until golden, drain.','Deep-fry aubergine until soft, drain.','Stir-fry garlic, add green pepper 1 min.','Return potato and aubergine, add soy, oyster sauce and sugar.','Toss over high heat 1 minute and serve.']},
  { name_en:'Stir-fried Bean Sprouts', name_zh:'清炒豆芽', category:'vegetable', calories:60, protein_g:3.5, carbs_g:5.0, fat_g:2.5, description:'Crisp and refreshing, ready in under 5 minutes.', ingredients:[{name_en:'Mung bean sprouts',name_zh:'绿豆芽',amount_g:300},{name_en:'Garlic',name_zh:'大蒜',amount_g:8,note:'sliced'},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:3,note:'optional'},{name_en:'Salt',name_zh:'盐',amount_g:3},{name_en:'Vinegar',name_zh:'醋',amount_g:5},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15}], steps:['Heat wok until smoking, add oil.','Fry garlic and chilli 15 seconds.','Add sprouts, toss vigorously over high heat 2 min.','Season with salt and vinegar, serve immediately.']},
  { name_en:'Braised Aubergine', name_zh:'红烧茄子', category:'vegetable', calories:150, protein_g:3.0, carbs_g:14.0, fat_g:8.0, description:'Tender aubergine braised to a glossy, umami-rich finish.', ingredients:[{name_en:'Aubergine',name_zh:'茄子',amount_g:400,note:'batons'},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Soy sauce',name_zh:'生抽',amount_g:20},{name_en:'Dark soy',name_zh:'老抽',amount_g:8},{name_en:'Sugar',name_zh:'糖',amount_g:8},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:6,note:'slurry'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:25}], steps:['Salt aubergine 10 min, squeeze out moisture.','Pan-fry in oil until golden on all sides.','Add garlic, soy sauces and sugar with 100ml water.','Simmer 5 min, thicken with cornstarch slurry.']},
  { name_en:'Hand-torn Cabbage', name_zh:'手撕包菜', category:'vegetable', calories:75, protein_g:2.5, carbs_g:9.0, fat_g:3.0, description:'Flash-fried with dried chilli and vinegar.', ingredients:[{name_en:'Chinese cabbage',name_zh:'包菜',amount_g:350,note:'hand-torn'},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Vinegar',name_zh:'醋',amount_g:8},{name_en:'Sugar',name_zh:'糖',amount_g:3},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15}], steps:['Heat wok until very hot, add oil.','Fry chilli and garlic 20 seconds.','Add cabbage, toss hard over maximum heat 2-3 min.','Splash in soy, vinegar and sugar, toss and serve.']},
  { name_en:'Steamed Egg Custard', name_zh:'水蒸蛋', category:'protein', protein_src:'egg', calories:120, protein_g:10.0, carbs_g:2.0, fat_g:7.5, description:'Silky smooth steamed egg, gentle and nourishing.', ingredients:[{name_en:'Eggs',name_zh:'鸡蛋',amount_g:150,note:'3 eggs'},{name_en:'Warm water',name_zh:'温水',amount_g:200,note:'1:1.5 ratio'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:8},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:5},{name_en:'Salt',name_zh:'盐',amount_g:2},{name_en:'Spring onion',name_zh:'葱',amount_g:8,note:'garnish'}], steps:['Beat eggs gently, mix in warm water and salt, strain.','Cover with cling film, poke holes.','Steam over medium-low heat 12 minutes.','Drizzle with soy sauce and sesame oil, garnish.']},
  { name_en:'Egg Fried Rice', name_zh:'蛋炒饭', category:'protein', protein_src:'egg', calories:350, protein_g:12.0, carbs_g:52.0, fat_g:9.0, description:'Best made with day-old cold rice.', ingredients:[{name_en:'Cooked rice',name_zh:'米饭',amount_g:300,note:'day-old, cold'},{name_en:'Eggs',name_zh:'鸡蛋',amount_g:100,note:'2 eggs, beaten'},{name_en:'Spring onion',name_zh:'葱',amount_g:20},{name_en:'Soy sauce',name_zh:'生抽',amount_g:12},{name_en:'Salt',name_zh:'盐',amount_g:2},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Heat oil until smoking, pour in egg, scramble lightly.','Add cold rice, break up all clumps over high heat.','Add soy sauce and salt, toss constantly 3 minutes.','Stir in spring onion and serve hot.']},
  { name_en:'Kung Pao Chicken', name_zh:'宫保鸡丁', category:'protein', protein_src:'chicken', calories:290, protein_g:26.0, carbs_g:14.0, fat_g:13.0, description:'Tender chicken with peanuts and the signature tingly sauce.', ingredients:[{name_en:'Chicken breast',name_zh:'鸡胸肉',amount_g:300,note:'diced 1.5cm'},{name_en:'Roasted peanuts',name_zh:'花生米',amount_g:50},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:8},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:3},{name_en:'Spring onion',name_zh:'葱',amount_g:20},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Vinegar',name_zh:'醋',amount_g:10},{name_en:'Sugar',name_zh:'糖',amount_g:8},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:8,note:'for marinade'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Marinate chicken in soy sauce and cornstarch 10 min.','Mix sauce: soy, vinegar, sugar, cornstarch and 2 tbsp water.','Stir-fry chilli and peppercorn in hot oil 20 seconds.','Add chicken, cook until white throughout.','Pour sauce over, toss to coat, add peanuts and spring onion.']},
  { name_en:'Three-cup Chicken', name_zh:'三杯鸡', category:'protein', protein_src:'chicken', calories:380, protein_g:30.0, carbs_g:8.0, fat_g:22.0, description:'Braised in equal parts soy, rice wine and sesame oil.', ingredients:[{name_en:'Chicken thighs',name_zh:'鸡腿',amount_g:400,note:'bone-in, chopped'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:45},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:45},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:45},{name_en:'Garlic',name_zh:'大蒜',amount_g:20,note:'whole cloves'},{name_en:'Ginger',name_zh:'姜',amount_g:15,note:'sliced'},{name_en:'Sugar',name_zh:'糖',amount_g:10},{name_en:'Thai basil',name_zh:'九层塔',amount_g:15}], steps:['Sear chicken pieces until golden on all sides.','Add garlic and ginger, fry 1 minute.','Pour in soy sauce, wine and sesame oil.','Braise covered on medium-low 20 minutes until sauce thickens.','Add sugar, toss well, finish with fresh basil.']},
  { name_en:'Braised Beef Brisket', name_zh:'红烧牛腩', category:'protein', protein_src:'beef', calories:420, protein_g:32.0, carbs_g:10.0, fat_g:26.0, description:'Meltingly tender brisket in a deep spiced soy braise.', ingredients:[{name_en:'Beef brisket',name_zh:'牛腩',amount_g:500,note:'4cm chunks'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:30},{name_en:'Dark soy',name_zh:'老抽',amount_g:15},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:30},{name_en:'Star anise',name_zh:'八角',amount_g:4},{name_en:'Cinnamon stick',name_zh:'肉桂',amount_g:5},{name_en:'Ginger',name_zh:'姜',amount_g:15},{name_en:'Sugar',name_zh:'糖',amount_g:12},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15}], steps:['Blanch brisket in cold water, bring to boil, drain and rinse.','Brown beef in hot oil until seared on all sides.','Add all aromatics and spices, fry 1 minute.','Add soy sauces, wine, sugar and enough water to cover.','Simmer covered 1.5 hours until fork-tender.']},
  { name_en:'Beef with Broccoli', name_zh:'西兰花炒牛肉', category:'protein', protein_src:'beef', calories:260, protein_g:24.0, carbs_g:11.0, fat_g:12.0, description:'Tender sliced beef and vibrant broccoli in oyster sauce.', ingredients:[{name_en:'Beef sirloin',name_zh:'牛里脊',amount_g:250,note:'thinly sliced'},{name_en:'Broccoli',name_zh:'西兰花',amount_g:200,note:'florets'},{name_en:'Oyster sauce',name_zh:'蚝油',amount_g:20},{name_en:'Soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:8,note:'for marinade'},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Marinate beef with soy, cornstarch and sesame oil 15 min.','Blanch broccoli 2 min, set aside.','Stir-fry beef over high heat until just cooked, set aside.','Fry garlic, return broccoli and beef, add oyster sauce.','Toss everything together and serve immediately.']},
  { name_en:'Lamb Cumin Stir-fry', name_zh:'孜然羊肉', category:'protein', protein_src:'lamb', calories:340, protein_g:27.0, carbs_g:6.0, fat_g:21.0, description:'Xinjiang-style fragrant lamb with cumin and chilli.', ingredients:[{name_en:'Lamb shoulder',name_zh:'羊肩肉',amount_g:300,note:'thinly sliced'},{name_en:'Cumin seeds',name_zh:'孜然粒',amount_g:6},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:6},{name_en:'Onion',name_zh:'洋葱',amount_g:80,note:'sliced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Coriander',name_zh:'香菜',amount_g:15,note:'garnish'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Marinate lamb with soy sauce and half the cumin 10 min.','Heat wok until smoking, sear lamb in batches, set aside.','Fry onion until softened, add remaining cumin and chilli.','Return lamb, toss on high heat 1 minute.','Finish with fresh coriander.']},
  { name_en:'Mutton Hot Pot Slices', name_zh:'涮羊肉', category:'protein', protein_src:'mutton', calories:310, protein_g:25.0, carbs_g:2.0, fat_g:20.0, description:'Classic Beijing-style quick-cook mutton.', ingredients:[{name_en:'Mutton leg',name_zh:'羊腿肉',amount_g:300,note:'paper-thin slices'},{name_en:'Sesame paste',name_zh:'芝麻酱',amount_g:30},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Fermented tofu',name_zh:'腐乳',amount_g:15},{name_en:'Chilli oil',name_zh:'辣椒油',amount_g:10,note:'to taste'},{name_en:'Spring onion',name_zh:'葱',amount_g:15}], steps:['Bring broth or water to a rolling boil.','Mix dipping sauce: sesame paste, soy, fermented tofu, chilli oil.','Swish mutton slices in hot broth 20-30 seconds.','Dip in sauce and enjoy with spring onion.']},

  // === Cantonese ===
  { name_en:'Cantonese Steamed Fish', name_zh:'清蒸鱼', category:'protein', protein_src:'chicken', calories:180, protein_g:28.0, carbs_g:2.0, fat_g:6.0, description:'Whole fish steamed over high heat and finished with soy and scalding oil — the pinnacle of Cantonese simplicity.', ingredients:[{name_en:'Sea bass',name_zh:'鲈鱼',amount_g:500,note:'cleaned and scored'},{name_en:'Ginger',name_zh:'姜',amount_g:15,note:'julienned'},{name_en:'Spring onion',name_zh:'葱',amount_g:20,note:'julienned'},{name_en:'Light soy sauce',name_zh:'生抽',amount_g:20},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:15},{name_en:'Sugar',name_zh:'糖',amount_g:4},{name_en:'Cooking oil',name_zh:'食用油',amount_g:25,note:'for sizzling'}], steps:['Place fish on a heatproof plate with ginger slices underneath.','Steam over vigorously boiling water for 8-10 minutes.','Discard any liquid, scatter spring onion and ginger julienne over fish.','Mix soy sauce and sugar, pour over fish.','Heat oil until smoking and pour directly over the aromatics to sizzle.']},

  { name_en:'Char Siu Pork', name_zh:'叉烧肉', category:'protein', protein_src:'pork', calories:370, protein_g:29.0, carbs_g:18.0, fat_g:18.0, description:'Cantonese BBQ pork with a lacquered, caramelised crust and juicy interior.', ingredients:[{name_en:'Pork shoulder',name_zh:'猪肩肉',amount_g:500,note:'cut into thick strips'},{name_en:'Hoisin sauce',name_zh:'海鲜酱',amount_g:30},{name_en:'Soy sauce',name_zh:'生抽',amount_g:20},{name_en:'Honey',name_zh:'蜂蜜',amount_g:25},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:20},{name_en:'Five-spice powder',name_zh:'五香粉',amount_g:3},{name_en:'Red fermented tofu',name_zh:'南乳',amount_g:20},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'}], steps:['Mix hoisin sauce, soy, honey, wine, five-spice powder, red tofu and garlic for marinade.','Marinate pork strips at least 4 hours or overnight in fridge.','Roast in oven at 220°C for 15 minutes, flip and brush with remaining marinade.','Roast another 10 minutes until edges char slightly.','Rest 5 minutes, slice and glaze with honey before serving.']},

  { name_en:'Steamed Spare Ribs with Black Bean', name_zh:'豉汁蒸排骨', category:'protein', protein_src:'pork', calories:290, protein_g:22.0, carbs_g:6.0, fat_g:18.0, description:'A dim sum classic — tender pork ribs with savoury fermented black beans.', ingredients:[{name_en:'Pork spare ribs',name_zh:'排骨',amount_g:400,note:'chopped into 3cm pieces'},{name_en:'Fermented black beans',name_zh:'豆豉',amount_g:20,note:'rinsed and roughly chopped'},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Ginger',name_zh:'姜',amount_g:8,note:'minced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Oyster sauce',name_zh:'蚝油',amount_g:10},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:10},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:8},{name_en:'Sugar',name_zh:'糖',amount_g:4},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:5}], steps:['Rinse ribs in cold water, pat dry.','Combine black beans, garlic, ginger, soy, oyster sauce, wine, cornstarch, sugar and sesame oil.','Toss ribs in the marinade, rest 20 minutes.','Spread ribs on a shallow plate.','Steam over high heat 15-18 minutes until cooked through.']},

  { name_en:'Wonton Soup', name_zh:'云吞汤', category:'protein', protein_src:'pork', calories:220, protein_g:15.0, carbs_g:24.0, fat_g:7.0, description:'Silky pork-shrimp wontons in a clear Cantonese broth.', ingredients:[{name_en:'Ground pork',name_zh:'猪绞肉',amount_g:200},{name_en:'Shrimp',name_zh:'虾仁',amount_g:100,note:'finely chopped'},{name_en:'Wonton wrappers',name_zh:'云吞皮',amount_g:150},{name_en:'Ginger',name_zh:'姜',amount_g:5,note:'minced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:12},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:5},{name_en:'Egg white',name_zh:'蛋白',amount_g:20},{name_en:'Chicken stock',name_zh:'鸡高汤',amount_g:600},{name_en:'Spring onion',name_zh:'葱',amount_g:15,note:'sliced for garnish'}], steps:['Combine pork, shrimp, ginger, soy sauce, sesame oil and egg white; stir until sticky.','Place a teaspoon of filling in the centre of each wrapper.','Moisten edges, fold into triangle, then bring corners together to seal.','Bring chicken stock to a simmer, season.','Cook wontons in boiling water 3-4 minutes until they float.','Transfer to bowls of hot stock and garnish with spring onion.']},

  { name_en:'Oyster Sauce Kai Lan', name_zh:'蚝油芥蓝', category:'vegetable', calories:85, protein_g:3.5, carbs_g:7.0, fat_g:4.5, description:'Cantonese broccoli glazed with oyster sauce — a restaurant staple.', ingredients:[{name_en:'Chinese broccoli (kai lan)',name_zh:'芥蓝',amount_g:350,note:'trimmed'},{name_en:'Oyster sauce',name_zh:'蚝油',amount_g:25},{name_en:'Sugar',name_zh:'糖',amount_g:4},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:8,note:'minced'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:10}], steps:['Blanch kai lan in boiling salted water with a splash of oil for 2 minutes.','Drain and arrange on serving plate.','Mix oyster sauce, sugar and a splash of water; heat in small pan until bubbling.','Pour sauce over vegetables and drizzle with sesame oil.']},

  { name_en:'Cantonese Roast Duck', name_zh:'烧鸭', category:'protein', protein_src:'chicken', calories:440, protein_g:31.0, carbs_g:5.0, fat_g:33.0, description:'Crispy-skinned roast duck with fragrant five-spice stuffing.', ingredients:[{name_en:'Duck',name_zh:'鸭子',amount_g:800,note:'half duck, cleaned'},{name_en:'Five-spice powder',name_zh:'五香粉',amount_g:4},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Honey',name_zh:'蜂蜜',amount_g:30},{name_en:'Rice vinegar',name_zh:'米醋',amount_g:15},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Ginger',name_zh:'姜',amount_g:10},{name_en:'Star anise',name_zh:'八角',amount_g:4}], steps:['Rub duck all over with five-spice, salt and soy sauce; refrigerate uncovered overnight.','Mix honey and rice vinegar; brush over skin.','Roast at 200°C for 20 minutes, baste with honey glaze every 10 minutes.','Roast a further 25-30 minutes until skin is deep mahogany and crisp.','Rest 10 minutes before chopping.']},

  // === Shanghainese ===
  { name_en:'Red-braised Pork Belly', name_zh:'红烧肉', category:'protein', protein_src:'pork', calories:510, protein_g:22.0, carbs_g:14.0, fat_g:40.0, description:'Shanghai-style melt-in-the-mouth pork belly in a rich, sweet-savoury glaze.', ingredients:[{name_en:'Pork belly',name_zh:'五花肉',amount_g:600,note:'3cm cubes'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:30},{name_en:'Dark soy sauce',name_zh:'老抽',amount_g:15},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:45},{name_en:'Rock sugar',name_zh:'冰糖',amount_g:30},{name_en:'Ginger',name_zh:'姜',amount_g:15,note:'sliced'},{name_en:'Spring onion',name_zh:'葱',amount_g:20,note:'tied in knot'},{name_en:'Star anise',name_zh:'八角',amount_g:4},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15}], steps:['Blanch pork belly in cold water, bring to boil, drain and rinse.','Caramelise rock sugar in hot oil until amber.','Add pork, toss to coat in caramel, 2 minutes.','Add soy sauces, wine, ginger, spring onion, star anise and water to cover.','Braise covered on low heat 1.5 hours.','Uncover and reduce sauce on high heat until glossy.']},

  { name_en:'Lion\'s Head Meatballs', name_zh:'狮子头', category:'protein', protein_src:'pork', calories:390, protein_g:25.0, carbs_g:12.0, fat_g:26.0, description:'Shanghai braised pork meatballs, so large they resemble a lion\'s mane.', ingredients:[{name_en:'Ground pork',name_zh:'猪绞肉',amount_g:400,note:'70% lean'},{name_en:'Water chestnuts',name_zh:'荸荠',amount_g:60,note:'finely chopped'},{name_en:'Ginger',name_zh:'姜',amount_g:10,note:'grated'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:20},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:15},{name_en:'Egg',name_zh:'鸡蛋',amount_g:55,note:'1 egg'},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:10},{name_en:'Napa cabbage',name_zh:'大白菜',amount_g:200,note:'large leaves'},{name_en:'Chicken stock',name_zh:'鸡高汤',amount_g:400}], steps:['Mix pork with water chestnuts, ginger, soy, wine, egg and cornstarch; stir vigorously until sticky.','Shape into 4 large balls (about 150g each).','Pan-fry meatballs until golden on all sides.','Line a clay pot with cabbage leaves.','Place meatballs on cabbage, add stock, braise covered on low heat 45 minutes.']},

  { name_en:'Shanghai Braised Pork Ribs', name_zh:'上海糖醋排骨', category:'protein', protein_src:'pork', calories:360, protein_g:21.0, carbs_g:22.0, fat_g:20.0, description:'Sweet and sour pork ribs, Shanghai style, with a glossy vinegar-soy glaze.', ingredients:[{name_en:'Pork ribs',name_zh:'猪排骨',amount_g:500,note:'individual ribs'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Rice vinegar',name_zh:'米醋',amount_g:25},{name_en:'Sugar',name_zh:'糖',amount_g:20},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:20},{name_en:'Ginger',name_zh:'姜',amount_g:10},{name_en:'Star anise',name_zh:'八角',amount_g:3},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15}], steps:['Blanch ribs, drain and pat dry.','Brown ribs in oil until golden.','Add ginger, star anise, soy sauce, vinegar, sugar, wine and enough water to cover.','Braise covered 40 minutes on medium-low heat.','Increase heat and reduce sauce until thick and glossy, turning ribs frequently.']},

  { name_en:'Drunk Chicken', name_zh:'醉鸡', category:'protein', protein_src:'chicken', calories:250, protein_g:28.0, carbs_g:3.0, fat_g:12.0, description:'Cold poached chicken marinated overnight in Shaoxing wine — a Shanghai appetiser.', ingredients:[{name_en:'Chicken thighs',name_zh:'鸡腿',amount_g:400,note:'boneless'},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:200},{name_en:'Chicken stock',name_zh:'鸡高汤',amount_g:100},{name_en:'Ginger',name_zh:'姜',amount_g:15,note:'sliced'},{name_en:'Spring onion',name_zh:'葱',amount_g:15},{name_en:'Salt',name_zh:'盐',amount_g:6},{name_en:'Wolfberries',name_zh:'枸杞',amount_g:10}], steps:['Poach chicken thighs in water with ginger and spring onion 15 minutes.','Remove and cool immediately in ice water, pat dry.','Roll each thigh tightly in cling film.','Mix wine, stock, salt and wolfberries for marinade.','Submerge chicken rolls in marinade, refrigerate at least 8 hours or overnight.','Unwrap, slice and serve cold with marinade spooned over.']},

  { name_en:'Stir-fried Pea Shoots', name_zh:'清炒豌豆苗', category:'vegetable', calories:65, protein_g:4.5, carbs_g:5.0, fat_g:3.0, description:'Tender pea shoots flash-fried with garlic — a delicate Shanghai spring dish.', ingredients:[{name_en:'Pea shoots',name_zh:'豌豆苗',amount_g:250,note:'tips only'},{name_en:'Garlic',name_zh:'大蒜',amount_g:12,note:'minced'},{name_en:'Salt',name_zh:'盐',amount_g:3},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:10}], steps:['Heat wok over high heat until smoking, add oil.','Fry garlic 15 seconds until fragrant.','Add pea shoots and toss continuously over maximum heat.','Splash in wine and season with salt.','Remove from heat as soon as shoots wilt, serve immediately.']},

  { name_en:'Shanghai Scallion Oil Noodles', name_zh:'葱油拌面', category:'vegetable', calories:310, protein_g:8.0, carbs_g:52.0, fat_g:9.0, description:'Chewy noodles tossed with deeply fragrant scallion-infused oil and soy sauce.', ingredients:[{name_en:'Thin wheat noodles',name_zh:'细面条',amount_g:200,note:'fresh or dried'},{name_en:'Spring onion',name_zh:'葱',amount_g:80,note:'2cm segments'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Dark soy sauce',name_zh:'老抽',amount_g:8},{name_en:'Sugar',name_zh:'糖',amount_g:8},{name_en:'Cooking oil',name_zh:'食用油',amount_g:60}], steps:['Fry spring onion segments in oil over low heat until deep golden-brown and crisp, about 20 minutes.','Strain oil into a bowl; discard or reserve the crispy onion.','Mix soy sauce, dark soy and sugar in a small bowl.','Cook noodles, drain, and toss with scallion oil and soy mixture.','Top with crispy onion and serve.']},

  // === Hunanese ===
  { name_en:'Chairman Mao\'s Red-braised Pork', name_zh:'毛氏红烧肉', category:'protein', protein_src:'pork', calories:530, protein_g:21.0, carbs_g:15.0, fat_g:43.0, description:'The fiery Hunanese take on red-braised pork with chillies.', ingredients:[{name_en:'Pork belly',name_zh:'五花肉',amount_g:600,note:'large cubes'},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:10},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:15},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Dark soy sauce',name_zh:'老抽',amount_g:15},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:30},{name_en:'Rock sugar',name_zh:'冰糖',amount_g:25},{name_en:'Ginger',name_zh:'姜',amount_g:15},{name_en:'Star anise',name_zh:'八角',amount_g:4},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Blanch pork belly, drain and rinse.','Brown in hot oil until golden.','Add doubanjiang and dried chilli, fry 1 minute.','Add ginger, star anise, soy sauces, wine and rock sugar.','Cover with water, braise 1.5 hours.','Reduce sauce until thick and caramelised.']},

  { name_en:'Hunan Steamed Fish Head', name_zh:'剁椒鱼头', category:'protein', protein_src:'chicken', calories:230, protein_g:27.0, carbs_g:5.0, fat_g:10.0, description:'A bold Hunanese dish — fish head blanketed with fiery chopped chilli paste.', ingredients:[{name_en:'Silver carp head',name_zh:'鱼头',amount_g:600,note:'split in half'},{name_en:'Pickled chopped chilli',name_zh:'剁椒',amount_g:80},{name_en:'Garlic',name_zh:'大蒜',amount_g:15,note:'minced'},{name_en:'Ginger',name_zh:'姜',amount_g:10,note:'minced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:15},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20},{name_en:'Spring onion',name_zh:'葱',amount_g:15,note:'garnish'}], steps:['Rub fish head with salt and Shaoxing wine, rest 10 minutes.','Mix pickled chilli with garlic and ginger.','Spread chilli mixture generously over fish head.','Steam over high heat 12-15 minutes.','Heat oil until smoking, pour over spring onion on fish to sizzle.']},

  { name_en:'Dry-fried Hunan Beef', name_zh:'湖南干炒牛肉', category:'protein', protein_src:'beef', calories:310, protein_g:28.0, carbs_g:7.0, fat_g:18.0, description:'Shredded beef stir-fried dry with celery and green chilli until fragrant.', ingredients:[{name_en:'Beef flank',name_zh:'牛腩肉',amount_g:300,note:'shredded along grain'},{name_en:'Celery',name_zh:'西芹',amount_g:100,note:'julienned'},{name_en:'Green chilli',name_zh:'青辣椒',amount_g:60,note:'sliced'},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:10},{name_en:'Cumin seeds',name_zh:'孜然粒',amount_g:3},{name_en:'Cooking oil',name_zh:'食用油',amount_g:25}], steps:['Marinate beef in soy sauce 10 minutes.','Stir-fry beef in very hot oil in batches until dry and lightly charred, set aside.','Fry doubanjiang and garlic 30 seconds.','Add celery and green chilli, toss on high heat 2 minutes.','Return beef, add cumin, toss vigorously 1 minute.']},

  { name_en:'Hunan Stir-fried Pork with Chilli', name_zh:'农家小炒肉', category:'protein', protein_src:'pork', calories:330, protein_g:23.0, carbs_g:8.0, fat_g:22.0, description:'Rustic Hunan pork belly with fresh green chilli — simple, smoky, irresistible.', ingredients:[{name_en:'Pork belly',name_zh:'五花肉',amount_g:300,note:'thin slices'},{name_en:'Long green chilli',name_zh:'长青辣椒',amount_g:120,note:'sliced'},{name_en:'Garlic',name_zh:'大蒜',amount_g:12},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:10},{name_en:'Cooking oil',name_zh:'食用油',amount_g:10}], steps:['Fry pork belly in a dry wok over medium heat until fat renders and edges curl.','Push pork to side, fry garlic and doubanjiang 30 seconds.','Add green chilli, stir-fry over high heat 2 minutes.','Add soy sauce, toss everything together and serve.']},

  { name_en:'Hunanese Lotus Root Stir-fry', name_zh:'爆炒莲藕', category:'vegetable', calories:130, protein_g:3.0, carbs_g:26.0, fat_g:3.5, description:'Crunchy lotus root stir-fried with vinegar and dried chilli.', ingredients:[{name_en:'Lotus root',name_zh:'莲藕',amount_g:300,note:'peeled, thin slices'},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Vinegar',name_zh:'醋',amount_g:15},{name_en:'Sugar',name_zh:'糖',amount_g:5},{name_en:'Soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Cooking oil',name_zh:'食用油',amount_g:15}], steps:['Soak lotus root slices in cold water 5 minutes to remove starch, drain.','Heat wok, fry chilli and garlic 20 seconds.','Add lotus root, toss over high heat 2-3 minutes.','Add soy sauce, vinegar and sugar, toss 30 seconds and serve.']},

  { name_en:'Braised Pork with Preserved Vegetables', name_zh:'梅菜扣肉', category:'protein', protein_src:'pork', calories:480, protein_g:22.0, carbs_g:12.0, fat_g:38.0, description:'Hunanese twice-cooked pork belly layered over tangy preserved mustard greens.', ingredients:[{name_en:'Pork belly',name_zh:'五花肉',amount_g:500,note:'whole piece'},{name_en:'Preserved mustard greens',name_zh:'梅菜',amount_g:150,note:'soaked and rinsed'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Dark soy sauce',name_zh:'老抽',amount_g:15},{name_en:'Sugar',name_zh:'糖',amount_g:12},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:20},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Boil whole pork belly 20 minutes; remove and rub dark soy all over skin while hot.','Deep-fry belly until skin blisters and turns deep reddish-brown; cool in ice water.','Slice into 1cm thick pieces.','Fry preserved greens with garlic, soy, sugar and wine 3 minutes.','Arrange pork slices skin-side down in bowl, top with greens.','Steam 1.5 hours, then invert onto plate to serve.']},

  // === Sichuan ===
  { name_en:'Dan Dan Noodles', name_zh:'担担面', category:'protein', protein_src:'pork', calories:450, protein_g:20.0, carbs_g:55.0, fat_g:16.0, description:'Street noodles with sesame sauce, chilli oil and seasoned pork.', ingredients:[{name_en:'Wheat noodles',name_zh:'面条',amount_g:200},{name_en:'Ground pork',name_zh:'猪绞肉',amount_g:120},{name_en:'Ya cai (Yibin preserved vegetable)',name_zh:'芽菜',amount_g:30},{name_en:'Sesame paste',name_zh:'芝麻酱',amount_g:30},{name_en:'Chilli oil',name_zh:'辣椒油',amount_g:20},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Sichuan peppercorn oil',name_zh:'花椒油',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:8,note:'minced'},{name_en:'Vinegar',name_zh:'醋',amount_g:8},{name_en:'Spring onion',name_zh:'葱',amount_g:15}], steps:['Brown pork with ya cai until fragrant and crisp.','Whisk sesame paste, chilli oil, soy, garlic, vinegar and peppercorn oil with a splash of hot water into a smooth sauce.','Cook noodles, drain, and divide between bowls.','Spoon sauce over noodles, top with pork mixture.','Garnish with spring onion and extra chilli oil.']},

  { name_en:'Sichuan Boiled Fish', name_zh:'水煮鱼', category:'protein', protein_src:'chicken', calories:280, protein_g:30.0, carbs_g:8.0, fat_g:14.0, description:'Silky fish fillets poached in a fiery, numbing chilli broth.', ingredients:[{name_en:'Grass carp fillet',name_zh:'草鱼片',amount_g:400,note:'thinly sliced'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:30},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:15},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:15},{name_en:'Ginger',name_zh:'姜',amount_g:10},{name_en:'Soybean sprouts',name_zh:'黄豆芽',amount_g:150},{name_en:'Egg white',name_zh:'蛋白',amount_g:20},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:10},{name_en:'Cooking oil',name_zh:'食用油',amount_g:60}], steps:['Marinate fish with egg white, cornstarch and salt 10 minutes.','Blanch bean sprouts and place in serving bowl.','Fry doubanjiang in oil 2 minutes, add garlic and ginger.','Add water or stock, bring to boil, simmer 5 minutes.','Slide fish slices in, cook gently 2-3 minutes until just opaque.','Pour fish and broth over sprouts.','Top with dried chilli and peppercorn, pour smoking hot oil over to sizzle.']},

  { name_en:'Twice-cooked Pork', name_zh:'回锅肉', category:'protein', protein_src:'pork', calories:420, protein_g:22.0, carbs_g:10.0, fat_g:32.0, description:'Pork belly first simmered then wok-fried with leek and doubanjiang.', ingredients:[{name_en:'Pork belly',name_zh:'五花肉',amount_g:400,note:'whole piece'},{name_en:'Garlic sprouts (leek)',name_zh:'蒜苗',amount_g:100,note:'sliced diagonally'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:25},{name_en:'Fermented black beans',name_zh:'豆豉',amount_g:10},{name_en:'Soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Sugar',name_zh:'糖',amount_g:5},{name_en:'Ginger',name_zh:'姜',amount_g:8},{name_en:'Cooking oil',name_zh:'食用油',amount_g:10}], steps:['Simmer pork belly whole in water with ginger 25 minutes until just cooked.','Cool, then slice into thin 3mm pieces.','Heat wok, add oil, fry doubanjiang and black beans 1 minute.','Add pork slices, stir-fry until edges curl and fat becomes translucent.','Add garlic sprouts, soy and sugar, toss over high heat 2 minutes.']},

  { name_en:'Sichuan Spicy Beef Skewers', name_zh:'串串香牛肉', category:'protein', protein_src:'beef', calories:295, protein_g:26.0, carbs_g:5.0, fat_g:18.0, description:'Tender beef skewers in a fragrant Sichuan spice paste — a Chengdu street classic.', ingredients:[{name_en:'Beef sirloin',name_zh:'牛里脊',amount_g:350,note:'cubed 2cm'},{name_en:'Chilli bean paste',name_zh:'辣豆瓣',amount_g:20},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:4},{name_en:'Cumin powder',name_zh:'孜然粉',amount_g:4},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Sesame oil',name_zh:'芝麻油',amount_g:8},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Thread beef cubes onto bamboo skewers.','Mix chilli paste, peppercorn, cumin, garlic, soy and sesame oil for marinade.','Coat skewers in marinade, rest 20 minutes.','Grill or pan-fry over high heat 3-4 minutes per side.','Brush with more marinade while cooking.']},

  { name_en:'Sichuan Boiled Beef', name_zh:'水煮牛肉', category:'protein', protein_src:'beef', calories:320, protein_g:29.0, carbs_g:9.0, fat_g:18.0, description:'Tender beef slices in a blazing, numbing Sichuan sauce over bean sprouts.', ingredients:[{name_en:'Beef sirloin',name_zh:'牛里脊',amount_g:350,note:'thinly sliced'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:30},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:5},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:12},{name_en:'Mung bean sprouts',name_zh:'绿豆芽',amount_g:150},{name_en:'Egg white',name_zh:'蛋白',amount_g:20},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:10},{name_en:'Garlic',name_zh:'大蒜',amount_g:15},{name_en:'Cooking oil',name_zh:'食用油',amount_g:60}], steps:['Marinate beef with egg white, cornstarch and salt.','Blanch bean sprouts, place in bowl.','Fry doubanjiang and garlic in oil, add 400ml water, simmer 3 minutes.','Cook beef slices in broth 2 minutes, pour over sprouts.','Top with dried chilli and peppercorns.','Pour smoking hot oil over everything to sizzle.']},

  { name_en:'Fish-fragrant Pork Shreds', name_zh:'鱼香肉丝', category:'protein', protein_src:'pork', calories:300, protein_g:22.0, carbs_g:16.0, fat_g:16.0, description:'A Sichuan classic with no fish — the sweet-sour-spicy sauce mimics classic fish seasoning.', ingredients:[{name_en:'Pork tenderloin',name_zh:'猪里脊',amount_g:250,note:'julienned'},{name_en:'Black fungus',name_zh:'木耳',amount_g:40,note:'soaked, shredded'},{name_en:'Bamboo shoots',name_zh:'竹笋',amount_g:80,note:'julienned'},{name_en:'Pickled chilli',name_zh:'泡辣椒',amount_g:20,note:'minced'},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Ginger',name_zh:'姜',amount_g:8,note:'minced'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:12},{name_en:'Vinegar',name_zh:'醋',amount_g:12},{name_en:'Sugar',name_zh:'糖',amount_g:10},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:8},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Marinate pork with soy and cornstarch.','Mix sauce: soy, vinegar, sugar, cornstarch and 3 tbsp water.','Stir-fry pork over high heat until cooked, set aside.','Fry pickled chilli, garlic and ginger 30 seconds.','Add fungus and bamboo shoots, toss 1 minute.','Return pork, pour sauce over, toss until glossy.']},

  { name_en:'Sichuan Cold Sesame Noodles', name_zh:'四川凉面', category:'vegetable', calories:380, protein_g:10.0, carbs_g:58.0, fat_g:13.0, description:'Cold wheat noodles dressed in a rich sesame-chilli sauce.', ingredients:[{name_en:'Wheat noodles',name_zh:'面条',amount_g:200},{name_en:'Sesame paste',name_zh:'芝麻酱',amount_g:35},{name_en:'Chilli oil',name_zh:'辣椒油',amount_g:20},{name_en:'Soy sauce',name_zh:'生抽',amount_g:15},{name_en:'Vinegar',name_zh:'醋',amount_g:10},{name_en:'Sichuan peppercorn oil',name_zh:'花椒油',amount_g:5},{name_en:'Garlic',name_zh:'大蒜',amount_g:8,note:'minced'},{name_en:'Sugar',name_zh:'糖',amount_g:5},{name_en:'Cucumber',name_zh:'黄瓜',amount_g:80,note:'julienned'},{name_en:'Carrot',name_zh:'胡萝卜',amount_g:50,note:'julienned'}], steps:['Cook noodles, drain and rinse under cold water; toss with a little oil.','Whisk sesame paste, chilli oil, soy, vinegar, peppercorn oil, garlic and sugar with 3 tbsp hot water.','Toss noodles with sauce.','Top with cucumber and carrot julienne; serve cold.']},

  { name_en:'Mapo Tofu with Minced Beef', name_zh:'牛肉麻婆豆腐', category:'protein', protein_src:'beef', calories:220, protein_g:18.0, carbs_g:8.0, fat_g:13.0, description:'A richer take on mapo tofu using seasoned minced beef instead of pork.', ingredients:[{name_en:'Silken tofu',name_zh:'嫩豆腐',amount_g:400,note:'cubed 2cm'},{name_en:'Ground beef',name_zh:'牛绞肉',amount_g:100},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:20},{name_en:'Fermented black beans',name_zh:'豆豉',amount_g:10},{name_en:'Garlic',name_zh:'大蒜',amount_g:10,note:'minced'},{name_en:'Ginger',name_zh:'姜',amount_g:8,note:'minced'},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:3,note:'ground'},{name_en:'Soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Cornstarch',name_zh:'淀粉',amount_g:8,note:'slurry'},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Boil tofu 1 minute in salted water, drain.','Brown beef in hot oil, set aside.','Fry doubanjiang and black beans 1 minute.','Add garlic and ginger, 30 seconds.','Add 200ml water, bring to simmer, slide in tofu.','Add soy, return beef, thicken with cornstarch slurry.','Finish with ground Sichuan peppercorn.']},

  { name_en:'Spicy Lamb Spine Hot Pot', name_zh:'麻辣羊蝎子', category:'protein', protein_src:'lamb', calories:395, protein_g:30.0, carbs_g:6.0, fat_g:27.0, description:'Sichuan-style braised lamb spine in a rich, numbing chilli broth.', ingredients:[{name_en:'Lamb spine',name_zh:'羊蝎子',amount_g:700,note:'chopped into sections'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:30},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:12},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:6},{name_en:'Star anise',name_zh:'八角',amount_g:4},{name_en:'Cinnamon',name_zh:'肉桂',amount_g:3},{name_en:'Ginger',name_zh:'姜',amount_g:15},{name_en:'Garlic',name_zh:'大蒜',amount_g:15},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:30},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Blanch lamb spine, drain and rinse.','Fry doubanjiang, chilli and peppercorn in oil 2 minutes.','Add ginger, garlic, star anise and cinnamon, fry 1 minute.','Add lamb, soy, wine and water to cover.','Braise covered over low heat 1.5 hours until meat falls from bone.']},

  { name_en:'Sichuan Dry Pot Cauliflower', name_zh:'干锅花椰菜', category:'vegetable', calories:175, protein_g:5.0, carbs_g:18.0, fat_g:9.0, description:'Cauliflower char-blistered in a dry pot with bacon and Sichuan aromatics.', ingredients:[{name_en:'Cauliflower',name_zh:'花椰菜',amount_g:400,note:'broken into florets'},{name_en:'Streaky bacon',name_zh:'培根',amount_g:60,note:'thin slices'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:15},{name_en:'Garlic',name_zh:'大蒜',amount_g:10},{name_en:'Ginger',name_zh:'姜',amount_g:6},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:5},{name_en:'Soy sauce',name_zh:'生抽',amount_g:10},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Blanch cauliflower 2 minutes, drain thoroughly.','Fry bacon in wok until lightly crisp, set aside.','Add oil and fry doubanjiang, garlic, ginger and chilli 1 minute.','Add cauliflower, fry over high heat until blistered, about 4 minutes.','Return bacon, add soy sauce, toss and serve in a cast iron pot.']},

  { name_en:'Sichuan Fragrant Lamb', name_zh:'香辣羊肉', category:'protein', protein_src:'lamb', calories:355, protein_g:28.0, carbs_g:7.0, fat_g:23.0, description:'Bone-in lamb pieces braised until tender in a Sichuan spice broth then finished with chilli.', ingredients:[{name_en:'Lamb shoulder',name_zh:'羊肩',amount_g:500,note:'bone-in pieces'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:20},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:4},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:8},{name_en:'Garlic',name_zh:'大蒜',amount_g:12},{name_en:'Ginger',name_zh:'姜',amount_g:12},{name_en:'Soy sauce',name_zh:'生抽',amount_g:20},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:25},{name_en:'Spring onion',name_zh:'葱',amount_g:20},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Blanch lamb pieces, drain.','Brown lamb in hot oil until golden.','Fry doubanjiang, peppercorn and dried chilli 1 minute.','Add garlic, ginger, soy, wine and enough water to cover.','Braise 1 hour until tender.','Garnish with spring onion.']},

  { name_en:'Sichuan Stewed Mutton', name_zh:'四川红焖羊肉', category:'protein', protein_src:'mutton', calories:375, protein_g:26.0, carbs_g:8.0, fat_g:26.0, description:'Mutton slowly stewed with Sichuan spices until fork-tender.', ingredients:[{name_en:'Mutton shoulder',name_zh:'羊肩肉',amount_g:500,note:'cubed'},{name_en:'Doubanjiang',name_zh:'豆瓣酱',amount_g:25},{name_en:'Sichuan peppercorn',name_zh:'花椒',amount_g:5},{name_en:'Star anise',name_zh:'八角',amount_g:4},{name_en:'Cinnamon stick',name_zh:'肉桂',amount_g:4},{name_en:'Dried chilli',name_zh:'干辣椒',amount_g:10},{name_en:'Ginger',name_zh:'姜',amount_g:15},{name_en:'Garlic',name_zh:'大蒜',amount_g:12},{name_en:'Soy sauce',name_zh:'生抽',amount_g:25},{name_en:'Dark soy sauce',name_zh:'老抽',amount_g:10},{name_en:'Shaoxing wine',name_zh:'绍兴酒',amount_g:30},{name_en:'Cooking oil',name_zh:'食用油',amount_g:20}], steps:['Blanch mutton in cold water, drain.','Brown in hot oil.','Fry doubanjiang, peppercorn and dried chilli 1 minute.','Add all spices, garlic, ginger, soy sauces and wine.','Cover with water, stew on low 1.5 hours until tender.','Remove lid and reduce sauce 15 minutes.']},
];
async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('TRUNCATE cooking_steps, ingredients, dishes RESTART IDENTITY CASCADE');
    for (const d of dishes) {
      const res = await client.query(`INSERT INTO dishes (name_en,name_zh,category,protein_src,description,calories,protein_g,carbs_g,fat_g) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[d.name_en,d.name_zh,d.category,(d as any).protein_src??null,d.description,d.calories,d.protein_g,d.carbs_g,d.fat_g]);
      const id = res.rows[0].id;
      for (const ing of d.ingredients) await client.query(`INSERT INTO ingredients (dish_id,name_en,name_zh,amount_g,note) VALUES ($1,$2,$3,$4,$5)`,[id,ing.name_en,ing.name_zh,ing.amount_g,ing.note??null]);
      for (let i=0;i<d.steps.length;i++) await client.query(`INSERT INTO cooking_steps (dish_id,step_no,instruction) VALUES ($1,$2,$3)`,[id,i+1,d.steps[i]]);
      console.log(`  ✅ ${d.name_en}`);
    }
    await client.query('COMMIT');
    console.log(`\n🌱 Seeded ${dishes.length} dishes.`);
  } catch(e) { await client.query('ROLLBACK'); throw e; }
  finally { client.release(); await pool.end(); }
}
seed();
