CREATE TABLE IF NOT EXISTS ingredients (
  id SERIAL PRIMARY KEY, dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  name_en VARCHAR(100) NOT NULL, name_zh VARCHAR(100) NOT NULL,
  amount_g DECIMAL(6,2) NOT NULL, note VARCHAR(200)
);
CREATE TABLE IF NOT EXISTS cooking_steps (
  id SERIAL PRIMARY KEY, dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  step_no INTEGER NOT NULL, instruction TEXT NOT NULL
);
